name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  playwright:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get purge -y man-db manpages
          sudo apt-get install -y chromium-browser x11-apps

      - name: Run Playwright Tests
        run: |
          sudo Xvfb :99 -ac &
          export DISPLAY=:99
          bash tests.sh

  tfjs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run TFJS Conversion Test
        run: bash test_convert_to_tfjs.sh

  tag:
    needs: [playwright, tfjs]
    runs-on: ubuntu-22.04
    if: ${{ success() }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create a new version
        run: |
          echo "Creating new version"
          git tag ${{ github.run_number }} || true
          git push origin --tags || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
