name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 2 * * 0'

jobs:
  playwright:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Clean system packages
        run: |
          sudo apt-get remove -y --purge man-db popularity-contest bsdmainutils
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get purge -y man-db manpages
          sudo apt-get install -y --no-install-recommends php sudo curl iproute2 python3 python3-pip python3-venv libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libatspi2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libcairo2 libpango-1.0-0 libasound2 libpango1.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libxcursor1 libx11-xcb1 
          curl -fsSL https://get.docker.com | sudo bash

      - name: Run Playwright Tests
        run: |
          Xvfb :99 -ac &
          export DISPLAY=:99
          echo "Running run_tests"
          bash -x run_tests --no-cache

  tfjsconverter:
    needs: [playwright]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run TFJS Conversion Test
        run: bash test_convert_to_tfjs

  tag:
    needs: [playwright, tfjsconverter]
    runs-on: ubuntu-22.04
    if: ${{ success() && github.event_name == 'push' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create a new version
        run: |
          echo "Creating new version"
          git tag ${{ github.run_number }} || true
          git push origin --tags || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
