name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 2 * * 0'

jobs:
  playwright:
    runs-on: ${{ matrix.os }}
    container:
      image: debian:bookworm-slim
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Clean system packages
        run: |
          df -h /
          apt-get remove -y --purge man-db popularity-contest bsdmainutils && \
          apt-get autoremove -y && apt-get clean && \
          rm -rf /var/lib/apt/lists/*
          df -h /
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get purge -y man-db manpages

      - name: Run Playwright Tests
        run: |
          Xvfb :99 -ac &
          export DISPLAY=:99
          bash tests.sh --no-cache

  tfjsconverter:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run TFJS Conversion Test
        run: bash test_convert_to_tfjs

  tag:
    needs: [playwright, tfjsconverter]
    runs-on: ubuntu-22.04
    if: ${{ success() && github.event_name == 'push' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create a new version
        run: |
          echo "Creating new version"
          git tag ${{ github.run_number }} || true
          git push origin --tags || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
